# Generated by Django 6.0.4 on 2026-04-16 09:36

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(choices=[('alava', 'Álava'), ('albacete', 'Albacete'), ('alicante', 'Alicante'), ('almeria', 'Almería'), ('asturias', 'Asturias'), ('avila', 'Ávila'), ('badajoz', 'Badajoz'), ('baleares', 'Islas Baleares'), ('barcelona', 'Barcelona'), ('burgos', 'Burgos'), ('caceres', 'Cáceres'), ('cadiz', 'Cádiz'), ('cantabria', 'Cantabria'), ('castellon', 'Castellón'), ('ciudad_real', 'Ciudad Real'), ('cordoba', 'Córdoba'), ('coruna', 'La Coruña'), ('cuenca', 'Cuenca'), ('girona', 'Gerona'), ('granada', 'Granada'), ('guadalajara', 'Guadalajara'), ('guipuzcoa', 'Guipúzcoa'), ('huelva', 'Huelva'), ('huesca', 'Huesca'), ('jaen', 'Jaén'), ('leon', 'León'), ('lleida', 'Lérida'), ('lugo', 'Lugo'), ('madrid', 'Madrid'), ('malaga', 'Málaga'), ('murcia', 'Murcia'), ('navarra', 'Navarra'), ('ourense', 'Orense'), ('palencia', 'Palencia'), ('las_palmas', 'Las Palmas'), ('pontevedra', 'Pontevedra'), ('la_rioja', 'La Rioja'), ('salamanca', 'Salamanca'), ('segovia', 'Segovia'), ('sevilla', 'Sevilla'), ('soria', 'Soria'), ('tarragona', 'Tarragona'), ('tenerife', 'Santa Cruz de Tenerife'), ('teruel', 'Teruel'), ('toledo', 'Toledo'), ('valencia', 'Valencia'), ('valladolid', 'Valladolid'), ('vizcaya', 'Vizcaya'), ('zamora', 'Zamora'), ('zaragoza', 'Zaragoza'), ('ceuta', 'Ceuta'), ('melilla', 'Melilla')], max_length=25)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('alergias', models.JSONField(default=list)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('acepta_notificaciones', models.BooleanField(default=False)),
                ('como_nos_conocio', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('amigos_otros', 'Amigos / Otros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-created_at'],
            },
        ),
    ]
