# Generated by Django 6.0.4 on 2026-04-10 22:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('alergias', models.JSONField(default=list)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], default='leve', max_length=10)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('acepta_notificaciones', models.BooleanField(default=False)),
                ('como_nos_conocio', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('amigos_otros', 'Amigos / Otros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-created_at'],
            },
        ),
    ]
