# Generated by Django 6.0.4 on 2026-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='severidad',
        ),
    ]
