# Generated by Django 6.0.4 on 2026-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_registro_severidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email', violation_error_message='Ya existe un registroooo con este email'),
        ),
    ]
