# Generated by Django 6.0.4 on 2026-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_email_registro_unique_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registro',
            name='unique_email',
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
