# Generated by Django 6.0.4 on 2026-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_registro_unique_email_alter_registro_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('alava', 'Álava'), ('albacete', 'Albacete'), ('alicante', 'Alicante'), ('almeria', 'Almería'), ('asturias', 'Asturias'), ('avila', 'Ávila'), ('badajoz', 'Badajoz'), ('baleares', 'Islas Baleares'), ('barcelona', 'Barcelona'), ('burgos', 'Burgos'), ('caceres', 'Cáceres'), ('cadiz', 'Cádiz'), ('cantabria', 'Cantabria'), ('castellon', 'Castellón'), ('ciudad_real', 'Ciudad Real'), ('cordoba', 'Córdoba'), ('coruna', 'La Coruña'), ('cuenca', 'Cuenca'), ('girona', 'Gerona'), ('granada', 'Granada'), ('guadalajara', 'Guadalajara'), ('guipuzcoa', 'Guipúzcoa'), ('huelva', 'Huelva'), ('huesca', 'Huesca'), ('jaen', 'Jaén'), ('leon', 'León'), ('lleida', 'Lérida'), ('lugo', 'Lugo'), ('madrid', 'Madrid'), ('malaga', 'Málaga'), ('murcia', 'Murcia'), ('navarra', 'Navarra'), ('ourense', 'Orense'), ('palencia', 'Palencia'), ('las_palmas', 'Las Palmas'), ('pontevedra', 'Pontevedra'), ('la_rioja', 'La Rioja'), ('salamanca', 'Salamanca'), ('segovia', 'Segovia'), ('sevilla', 'Sevilla'), ('soria', 'Soria'), ('tarragona', 'Tarragona'), ('tenerife', 'Santa Cruz de Tenerife'), ('teruel', 'Teruel'), ('toledo', 'Toledo'), ('valencia', 'Valencia'), ('valladolid', 'Valladolid'), ('vizcaya', 'Vizcaya'), ('zamora', 'Zamora'), ('zaragoza', 'Zaragoza'), ('ceuta', 'Ceuta'), ('melilla', 'Melilla')], max_length=25),
        ),
    ]
