ALERGENO_MAP = {
    'Gramíneas':     'grass_pollen',
    'Olivo':         'olive_pollen',
    'Abedul':        'birch_pollen',
    'Artemisa':      'mugwort_pollen',
    'Ambrosía':      'ragweed_pollen',
    'Aliso':         'alder_pollen',
    'Ácaros':        None,
    'Pelo de gato':  None,
    'Pelo de perro': None,
}

PROVINCIA_CHOICES = [
    ('alava', 'Álava'),
    ('albacete', 'Albacete'),
    ('alicante', 'Alicante'),
    ('almeria', 'Almería'),
    ('asturias', 'Asturias'),
    ('avila', 'Ávila'),
    ('badajoz', 'Badajoz'),
    ('baleares', 'Islas Baleares'),
    ('barcelona', 'Barcelona'),
    ('burgos', 'Burgos'),
    ('caceres', 'Cáceres'),
    ('cadiz', 'Cádiz'),
    ('cantabria', 'Cantabria'),
    ('castellon', 'Castellón'),
    ('ciudad_real', 'Ciudad Real'),
    ('cordoba', 'Córdoba'),
    ('coruna', 'La Coruña'),
    ('cuenca', 'Cuenca'),
    ('girona', 'Gerona'),
    ('granada', 'Granada'),
    ('guadalajara', 'Guadalajara'),
    ('guipuzcoa', 'Guipúzcoa'),
    ('huelva', 'Huelva'),
    ('huesca', 'Huesca'),
    ('jaen', 'Jaén'),
    ('leon', 'León'),
    ('lleida', 'Lérida'),
    ('lugo', 'Lugo'),
    ('madrid', 'Madrid'),
    ('malaga', 'Málaga'),
    ('murcia', 'Murcia'),
    ('navarra', 'Navarra'),
    ('ourense', 'Orense'),
    ('palencia', 'Palencia'),
    ('las_palmas', 'Las Palmas'),
    ('pontevedra', 'Pontevedra'),
    ('la_rioja', 'La Rioja'),
    ('salamanca', 'Salamanca'),
    ('segovia', 'Segovia'),
    ('sevilla', 'Sevilla'),
    ('soria', 'Soria'),
    ('tarragona', 'Tarragona'),
    ('tenerife', 'Santa Cruz de Tenerife'),
    ('teruel', 'Teruel'),
    ('toledo', 'Toledo'),
    ('valencia', 'Valencia'),
    ('valladolid', 'Valladolid'),
    ('vizcaya', 'Vizcaya'),
    ('zamora', 'Zamora'),
    ('zaragoza', 'Zaragoza'),
    ('ceuta', 'Ceuta'),
    ('melilla', 'Melilla'),
]