export const CIUDADES = [
  { label: "Álava", value: "alava" },
  { label: "Albacete", value: "albacete" },
  { label: "Alicante", value: "alicante" },
  { label: "Almería", value: "almeria" },
  { label: "Asturias", value: "asturias" },
  { label: "Ávila", value: "avila" },
  { label: "Badajoz", value: "badajoz" },
  { label: "Baleares", value: "baleares" },
  { label: "Barcelona", value: "barcelona" },
  { label: "Burgos", value: "burgos" },
  { label: "Cáceres", value: "caceres" },
  { label: "Cádiz", value: "cadiz" },
  { label: "Cantabria", value: "cantabria" },
  { label: "Castellón", value: "castellon" },
  { label: "Ciudad Real", value: "ciudad_real" },
  { label: "Córdoba", value: "cordoba" },
  { label: "La Coruña", value: "coruna" },
  { label: "Cuenca", value: "cuenca" },
  { label: "Gerona", value: "girona" },
  { label: "Granada", value: "granada" },
  { label: "Guadalajara", value: "guadalajara" },
  { label: "Guipúzcoa", value: "guipuzcoa" },
  { label: "Huelva", value: "huelva" },
  { label: "Huesca", value: "huesca" },
  { label: "Jaén", value: "jaen" },
  { label: "León", value: "leon" },
  { label: "Lérida", value: "lleida" },
  { label: "Lugo", value: "lugo" },
  { label: "Madrid", value: "madrid" },
  { label: "Málaga", value: "malaga" },
  { label: "Murcia", value: "murcia" },
  { label: "Navarra", value: "navarra" },
  { label: "Orense", value: "ourense" },
  { label: "Palencia", value: "palencia" },
  { label: "Las Palmas", value: "las_palmas" },
  { label: "Pontevedra", value: "pontevedra" },
  { label: "La Rioja", value: "la_rioja" },
  { label: "Salamanca", value: "salamanca" },
  { label: "Segovia", value: "segovia" },
  { label: "Sevilla", value: "sevilla" },
  { label: "Soria", value: "soria" },
  { label: "Tarragona", value: "tarragona" },
  { label: "S.C. Tenerife", value: "tenerife" },
  { label: "Teruel", value: "teruel" },
  { label: "Toledo", value: "toledo" },
  { label: "Valencia", value: "valencia" },
  { label: "Valladolid", value: "valladolid" },
  { label: "Vizcaya", value: "vizcaya" },
  { label: "Zamora", value: "zamora" },
  { label: "Zaragoza", value: "zaragoza" },
  { label: "Ceuta", value: "ceuta" },
  { label: "Melilla", value: "melilla" },
];

export const CIUDADES_VALUES = CIUDADES.map((ciudad) => ciudad.value);

export const CIUDADES_LABELS = CIUDADES.map((ciudad) => ciudad.label);
